disabled_rules:
  - class_delegate_protocol
  - control_statement
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - identifier_name
  - implicit_getter
  - legacy_constant
  - legacy_constructor
  - line_length
  - opening_brace
  - redundant_optional_initialization
  - redundant_string_enum_value
  - trailing_newline
  - trailing_whitespace
  - type_body_length
  - type_name
  - unneeded_break_in_switch
  - unused_closure_parameter
  - unused_optional_binding
  - vertical_whitespace
  - weak_computed_property
  - weak_delegate

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - MoJobTests
  - MoJobUITests
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard

